"""Emit constants.generated.ts — lookup tables and derived constants."""
from pathlib import Path

from generate.emitters.ts_helpers import ts_edge_type_name, ts_key, ts_record, ts_string_array, ts_type_names
from generate.ir import ElementDef
def emit_constants(
    elements: dict[str, ElementDef],
    descendants: dict[str, list[str]],
    ancestors: dict[str, list[str]],
    root_element: str,
    singleton_elements: list[str],
    out: Path,
) -> None:
    """Write constants.generated.ts with all lookup tables."""
    names = sorted(elements.keys())
    type_names = ts_type_names(names)
    edge_types = sorted(
        ts_edge_type_name(type_names, name, parent)
        for name in names
        for parent in elements[name].definitions_by_parent
    )
    imports = ', '.join(['AvailableElement', 'AttributesOf', 'AttributesByParent', *edge_types])

    lines = [
        '// Auto-generated by generate.py — do not edit',
        '',
        f"import type {{ {imports} }} from './types.generated'",
        '',
        f'export const ELEMENT_NAMES = {ts_string_array(names)} as const',
        '',
        f'export const CHILDREN = {ts_record(_child_map(elements))} as const',
        '',
        f'export const PARENTS = {ts_record(_parent_map(elements))} as const',
        '',
        f'export const DESCENDANTS = {ts_record(descendants)} as const',
        '',
        f'export const ANCESTORS = {ts_record(ancestors)} as const',
        '',
        f"export const ROOT_ELEMENT = '{root_element}' as const",
        '',
        f'export const SINGLETON_ELEMENTS = {ts_string_array(singleton_elements)} as const',
        '',
        f'const ATTRIBUTES_BY_TAG = {_attr_obj_ts(elements)} as const',
        '',
        '/**',
        ' * Attribute skeletons: one key per attribute name, typed for the type system; what an attribute',
        ' * is (required, fixed, facets) lives in `DEFINITION`. `byTag` is the shape of an element wherever',
        ' * it appears; `byParent` its shape AS DECLARED UNDER each parent, the same object where the schema',
        ' * declares the tag once, its own where a homonym differs.',
        ' */',
        'export const ATTRIBUTES = {',
        '\tbyTag: ATTRIBUTES_BY_TAG,',
        f'\tbyParent: {_attr_by_parent_ts(elements, type_names)} satisfies AttributesByParent,',
        '} as const',
        '',
        f'export const REQUIRED_ATTRIBUTES = {ts_record(_required_attr_map(elements))} as const satisfies Record<AvailableElement, readonly string[]>',
        '',
    ]

    out.write_text('\n'.join(lines), encoding='utf-8')
def _child_map(elements: dict[str, ElementDef]) -> dict[str, list[str]]:
    """Element name → sorted child element names."""
    return {name: list(e.child_sequence) for name, e in elements.items()}
def _parent_map(elements: dict[str, ElementDef]) -> dict[str, list[str]]:
    """Element name → sorted parent element names."""
    return {name: sorted(e.parents) for name, e in elements.items()}


def _attr_obj_ts(elements: dict[str, ElementDef]) -> str:
    """The by-tag skeletons: each element → keyed record with '' values cast via AttributesOf."""
    lines = ['{']
    for name in sorted(elements.keys()):
        elem = elements[name]
        if not elem.attr_sequence:
            lines.append(f"\t{ts_key(name)}: {{}} as AttributesOf<'{name}'>,")
        else:
            lines.append(f'\t{ts_key(name)}: {{')
            for attr_name in elem.attr_sequence:
                key = ts_key(attr_name)
                lines.append(f"\t\t{key}: '' as string,")
            lines.append(f"\t}} as AttributesOf<'{name}'>,")
    lines.append('}')
    return '\n'.join(lines)


def _attr_by_parent_ts(elements: dict[str, ElementDef], type_names: dict[str, str]) -> str:
    """The by-parent skeletons: one row per parent, one entry per child edge - a reference to the
    by-tag object for an element declared once, its own skeleton where a homonym differs."""
    lines = ['{']
    for parent in sorted(elements):
        children = [c for c in elements[parent].child_sequence if c in elements]
        if not children:
            continue
        lines.append(f'\t\t{ts_key(parent)}: {{')
        for child in children:
            declared = elements[child].definitions_by_parent.get(parent)
            if declared is None:
                lines.append(f'\t\t\t{ts_key(child)}: ATTRIBUTES_BY_TAG{_member(child)},')
            else:
                skeleton = _skeleton(declared.attr_sequence)
                lines.append(f'\t\t\t{ts_key(child)}: {skeleton} as {ts_edge_type_name(type_names, child, parent)},')
        lines.append('\t\t},')
    lines.append('\t}')
    return '\n'.join(lines)


def _member(name: str) -> str:
    """`.name`, or `['a-b']` for a name that is not an identifier."""
    return f'.{name}' if name.isidentifier() else f'[{ts_key(name)}]'


def _skeleton(attr_sequence: list[str]) -> str:
    if not attr_sequence:
        return '{}'
    inner = ', '.join(f"{ts_key(a)}: '' as string" for a in attr_sequence)
    return f'{{ {inner} }}'
def _required_attr_map(elements: dict[str, ElementDef]) -> dict[str, list[str]]:
    """Element name → required attribute names (sorted)."""
    return {
        name: sorted(aname for aname, adef in e.attributes.items() if adef.required)
        for name, e in elements.items()
    }
