"""Emit constants.generated.ts — lookup tables and derived constants."""
from pathlib import Path

from generate.emitters.ts_helpers import ts_key, ts_record, ts_string_array
from generate.ir import ElementDef
def emit_constants(
    elements: dict[str, ElementDef],
    descendants: dict[str, list[str]],
    ancestors: dict[str, list[str]],
    root_element: str,
    singleton_elements: list[str],
    out: Path,
) -> None:
    """Write constants.generated.ts with all lookup tables."""
    names = sorted(elements.keys())

    lines = [
        '// Auto-generated by generate.py — do not edit',
        '',
        "import type { AvailableElement, AttributesOf } from './types.generated'",
        '',
        f'export const ELEMENT_NAMES = {ts_string_array(names)} as const',
        '',
        f'export const CHILDREN = {ts_record(_child_map(elements))} as const',
        '',
        f'export const PARENTS = {ts_record(_parent_map(elements))} as const',
        '',
        f'export const DESCENDANTS = {ts_record(descendants)} as const',
        '',
        f'export const ANCESTORS = {ts_record(ancestors)} as const',
        '',
        f"export const ROOT_ELEMENT = '{root_element}' as const",
        '',
        f'export const SINGLETON_ELEMENTS = {ts_string_array(singleton_elements)} as const',
        '',
        f'export const ATTRIBUTES = {_attr_obj_ts(elements)} as const',
        '',
        f'export const REQUIRED_ATTRIBUTES = {ts_record(_required_attr_map(elements))} as const satisfies Record<AvailableElement, readonly string[]>',
        '',
    ]

    out.write_text('\n'.join(lines), encoding='utf-8')
def _child_map(elements: dict[str, ElementDef]) -> dict[str, list[str]]:
    """Element name → sorted child element names."""
    return {name: list(e.child_sequence) for name, e in elements.items()}
def _parent_map(elements: dict[str, ElementDef]) -> dict[str, list[str]]:
    """Element name → sorted parent element names."""
    return {name: sorted(e.parents) for name, e in elements.items()}
def _attr_obj_ts(elements: dict[str, ElementDef]) -> str:
    """Generate ATTRIBUTES runtime object: each element → keyed record with '' values cast via AttributesOf."""
    lines = ['{']
    for name in sorted(elements.keys()):
        elem = elements[name]
        if not elem.attr_sequence:
            lines.append(f"\t{name}: {{}} as AttributesOf<'{name}'>,")
        else:
            lines.append(f'\t{name}: {{')
            for attr_name in elem.attr_sequence:
                key = ts_key(attr_name)
                lines.append(f"\t\t{key}: '' as string,")
            lines.append(f"\t}} as AttributesOf<'{name}'>,")
    lines.append('}')
    return '\n'.join(lines)
def _required_attr_map(elements: dict[str, ElementDef]) -> dict[str, list[str]]:
    """Element name → required attribute names (sorted)."""
    return {
        name: sorted(aname for aname, adef in e.attributes.items() if adef.required)
        for name, e in elements.items()
    }
