"""Emit definition.generated.ts — the DEFINITION constant."""
from pathlib import Path

from generate.emitters.ts_helpers import ts_element_body, ts_key
from generate.ir import ElementDef
def emit_definition(elements: dict[str, ElementDef], out: Path) -> None:
    """Write the DEFINITION constant to definition.generated.ts.

    Sparse — only non-default fields emitted per element. A homonym's definition under a parent
    is written on the edge from that parent, next to the child's occurrence.
    """
    lines = [
        '// Auto-generated by generate.py — do not edit',
        '',
        'export const DEFINITION = {',
    ]

    for name in sorted(elements):
        elem = elements[name]
        edge_definitions = {
            child: elements[child].definitions_by_parent[name]
            for child in elem.child_sequence
            if child in elements and name in elements[child].definitions_by_parent
        }
        lines.append(f'\t{ts_key(name)}: {{')
        lines.extend(ts_element_body(elem, '\t\t', edge_definitions))
        lines.append('\t},')

    lines.append('} as const')
    lines.append('')

    out.write_text('\n'.join(lines), encoding='utf-8')
