"""Emit definition.generated.ts — the DEFINITION constant."""
from pathlib import Path

from generate.emitters.ts_helpers import (
    ts_attr_block,
    ts_child_block,
    ts_constraints,
    ts_namespace,
    ts_string,
    ts_text_content,
)
from generate.ir import ElementDef
def emit_definition(elements: dict[str, ElementDef], out: Path) -> None:
    """Write the DEFINITION constant to definition.generated.ts.

    Sparse — only non-default fields emitted per element.
    """
    lines = [
        '// Auto-generated by generate.py — do not edit',
        '',
        'export const DEFINITION = {',
    ]

    for name in sorted(elements):
        elem = elements[name]
        lines.append(f'\t{name}: {{')
        lines.append(f"\t\ttag: '{name}',")
        lines.append(f'\t\tnamespace: {ts_namespace(elem.namespace)},')
        if elem.documentation:
            lines.append(f'\t\tdocumentation: {ts_string(elem.documentation)},')
        lines.append(f'\t\tparents: {_inline_string_array(elem.parents)},')
        lines.append(f'\t\tattributes: {ts_attr_block(elem, "\t\t\t")},')
        lines.append(f'\t\tchildren: {ts_child_block(elem, "\t\t\t")},')
        if elem.constraints:
            lines.append(f'\t\tconstraints: {ts_constraints(elem.constraints, "\t\t\t")},')
        if elem.text_content:
            lines.append(f'\t\ttextContent: {ts_text_content(elem.text_content, "\t\t\t")},')
        lines.append('\t},')

    lines.append('} as const')
    lines.append('')

    out.write_text('\n'.join(lines), encoding='utf-8')
def _inline_string_array(items: list[str]) -> str:
    """Short array on one line."""
    if not items:
        return '[]'
    inner = ', '.join(f"'{i}'" for i in items)
    return f'[{inner}]'
