"""Emit types.generated.ts — per-element attribute type interfaces."""
from pathlib import Path

from generate.emitters.ts_helpers import ts_key
from generate.ir import AttributeDef, ElementDef
def emit_types(elements: dict[str, ElementDef], out: Path) -> None:
    """Write types.generated.ts with attribute type interfaces.

    Namespace-qualified keys (e.g. 'eIEC61850-6-100:version') are quoted in the TS interface.
    Enumeration facets generate union types.
    """
    lines = [
        '// Auto-generated by generate.py — do not edit',
        '',
        "import type { ELEMENT_NAMES, REQUIRED_ATTRIBUTES } from './constants.generated'",
        '',
        'export type AvailableElement = (typeof ELEMENT_NAMES)[number]',
        '',
    ]

    sorted_names = sorted(elements)

    for name in sorted_names:
        elem = elements[name]
        lines.append(f'export type Attributes{name} = {{')
        for attr_name in elem.attr_sequence:
            attr = elem.attributes[attr_name]
            ts_type = _attr_to_ts_type(attr)
            optional = '?' if not attr.required else ''
            key = ts_key(attr_name)
            lines.append(f'\t{key}{optional}: {ts_type}')
        lines.append('}')
        lines.append('')

    lines.append('export type AttributesMap = {')
    for name in sorted_names:
        lines.append(f'\t{name}: Attributes{name}')
    lines.append('}')
    lines.append('')
    lines.append('export type AttributesOf<T extends AvailableElement> = AttributesMap[T]')
    lines.append('')
    lines.append('export type RequiredAttributeNames<T extends AvailableElement> =')
    lines.append('\t(typeof REQUIRED_ATTRIBUTES)[T][number]')
    lines.append('export type OptionalAttributeNames<T extends AvailableElement> = Exclude<')
    lines.append('\tkeyof AttributesOf<T>,')
    lines.append('\tRequiredAttributeNames<T>')
    lines.append('>')
    lines.append('')

    out.write_text('\n'.join(lines), encoding='utf-8')
def _attr_to_ts_type(attr: AttributeDef) -> str:
    """Generate a TS type annotation from an attribute definition.

    - Enumerations → union of literal strings + (string & {}) for extensibility
    - Fixed values → literal string type
    - Default → string
    """
    facets = attr.facets

    if facets and facets.enumeration:
        literals = ' | '.join(f"'{v}'" for v in facets.enumeration)
        return f'{literals} | (string & {{}})'

    if attr.fixed:
        return f"'{attr.fixed}'"

    return 'string'
