name: Publish @dialecte/create

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  install:
    name: Install Dependencies
    uses: ./.github/workflows/_install.yml

  build:
    name: Build CLI
    needs: install
    uses: ./.github/workflows/_build.yml

  test:
    name: CLI Smoke Test
    needs: install
    uses: ./.github/workflows/_test.yml

  test-engine:
    name: Python Engine Tests
    uses: ./.github/workflows/_test-engine.yml

  version:
    name: Check Version
    uses: ./.github/workflows/_check-npm-version.yml

  extract-version:
    name: Extract Version
    uses: ./.github/workflows/_extract-version.yml

  deploy:
    name: Publish to NPM
    if: needs.version.outputs.version_changed == 'true'
    needs:
      - build
      - test
      - test-engine
      - version
    uses: ./.github/workflows/_publish.yml
    secrets:
      npm-token: ${{ secrets.NPM_TOKEN }}

  create-release-tag:
    name: Create Release Tag
    if: needs.version.outputs.version_changed == 'true'
    needs:
      - version
      - extract-version
      - deploy
    uses: ./.github/workflows/_tag-release.yml
    with:
      version: ${{ needs.extract-version.outputs.version }}
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
